 
SET QT_BIN_PATH=%1
SET BAT_PLUGIN_NAME=%2
SET BAT_PLUGIN_VERSION=%3
SET BAT_PLUGIN_PARENT_PATH=%4
SET BAT_PLUGIN_QMLTYPES_PATH=%5
 
echo "------create_qmltypes-------"
echo %QT_BIN_PATH%
echo %BAT_PLUGIN_NAME%
echo %BAT_PLUGIN_VERSION%
echo %BAT_PLUGIN_PARENT_PATH%
echo %BAT_PLUGIN_QMLTYPES_PATH%
echo "-------------"
 
%QT_BIN_PATH%\qmlplugindump.exe -nonrelocatable  %BAT_PLUGIN_NAME% %BAT_PLUGIN_VERSION% %BAT_PLUGIN_PARENT_PATH%  >  %BAT_PLUGIN_QMLTYPES_PATH%